[project]
name = "torivumab-nsclc-301"

[dependencies]
admiral = "*"
admiralonco = "*"
arrow = "*"
diffdf = "*"
digest = "*"
dplyr = "*"
flextable = "*"
ggplot2 = "*"
htmltools = "*"
kableExtra = "*"
knitr = "*"
labelled = "*"
lubridate = "*"
metacore = "*"
officer = "*"
openxlsx = "*"
openxlsx2 = "*"
patchwork = "*"
purrr = "*"
readr = "*"
rmarkdown = "*"
rstudioapi = "*"
rtables = "*"
scales = "*"
stringr = "*"
survRM2 = "*"
survival = "*"
tern = "*"
tibble = "*"
tidyr = "*"
waldo = "*"
xml2 = "*"
xportr = "*"
yaml = "*"
